image: go1.3
git:
  path: github.com/drone/drone
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - sudo apt-get -y install zip libsqlite3-dev sqlite3 rpm 1> /dev/null 2> /dev/null
  - gem install fpm
  - rbenv rehash
  - make deps
  - make test
  - make test_postgres
  - make test_mysql
  - make packages
services:
  - postgres
  - mysql
notify:
  email:
    recipients:
      - rud5gmobile@gmail.com


